Traceback (most recent call last):
  File "/home/pi/git/rasp/new_test.py", line 23, in transcribe_mic
    audio = recog.listen(source, timeout=3)
  File "/home/pi/.local/lib/python3.9/site-packages/speech_recognition/__init__.py", line 465, in listen
    assert source.stream is not None, "Audio source must be entered before listening, see documentation for ``AudioSource``; are you using ``source`` outside of a ``with`` statement?"
AssertionError: Audio source must be entered before listening, see documentation for ``AudioSource``; are you using ``source`` outside of a ``with`` statement?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/git/rasp/new_test.py", line 50, in <module>
    main()
  File "/home/pi/git/rasp/new_test.py", line 47, in main
    transcribe_mic()
  File "/home/pi/git/rasp/new_test.py", line 44, in transcribe_mic
    os.system('cvlc --play-and-exit test.mp3')
  File "/home/pi/.local/lib/python3.9/site-packages/speech_recognition/__init__.py", line 189, in __exit__
    self.stream.close()
AttributeError: 'NoneType' object has no attribute 'close'